Console.WriteLine("Введите значение:");
string a = Convert.ToString(Console.ReadLine()); 
Console.WriteLine("Введите значение:");
string b = Convert.ToString(Console.ReadLine()); 
Console.WriteLine("Введите значение:");
string c = Convert.ToString(Console.ReadLine());
 Console.WriteLine("Введите значение:");
string d = Convert.ToString(Console.ReadLine());
 Console.WriteLine("Введите значение:");
string e = Convert.ToString(Console.ReadLine()); 
string[] array = new string [5];
array[0] = a;
array[1] = b;
array[2] = c;
array[3] = d;
array[4] = e;
string [] arr = new string[5];
